### ISSUE TITLE
Red/Green/Blue/Amber dimming

### ISSUE THREAD

**Issue by stoehrmark** [jnimmo/hass-dmx#18]
Instead of White can Amber be added. 
Maybe something like rgba, rgba_auto, drgba, etc

[RGBA Fixture](https://www.bhphotovideo.com/c/product/1141713-REG/blizzard_lighting_the_puck_rgba_unplugged_battery_power_version_puck.html)

![blizzard_lighting_the_puck_rgba_unplugged_battery_power_version_puck_1430326233000_1141713](https://user-images.githubusercontent.com/24501941/49975228-faf64700-ff0a-11e8-943f-d4e23c6b4373.jpg)

**Comment by stoehrmark** [comment]
This fixture and many like it have 4 dedicated channels including Amber. They are independently dimmable. If the RGBA_AUTO could make amber instead of using red and green to make amber. It could work better with this 4 channel fixture.
Thanks for all your hard work on this project.
1+

**Comment by stoehrmark** [comment]
Awesome I will give it a try and let you know Thanks

**Comment by stoehrmark** [comment]
Tested and it works great. As expected the colors are matching the selections. Thanks for this addition

**Comment by jnimmo** [comment]
Fantastic, glad it works! Thanks for letting me know
