### ISSUE TITLE
Integration dmx not found when trying to verify its light platform.

### ISSUE THREAD

**Issue by TychoWerner** [jnimmo/hass-dmx#21]
With new changes to home-assistant integrations are required to get a manifest.
Docs can be found below.
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

Thanks in advance!

**Comment by arretx** [comment]
Not sure what this means, but my DMX lights just went AWOL with the most recent update.  What needs to happen?

**Comment by TychoWerner** [comment]
I'm not sure yet, I am currently trying to get it working again.
I've tried to make my own manifest.json & a __init__.py file but so far I have only seem to bricked my hass.io :/

**Comment by arretx** [comment]
Not sure about the init.py as I don't program, but I tried the manifest.json thing and it hosed my startup.  Removed the json file and it fired up again, but now I've lost the ability to automate the house lights in our sanctuary and we have no other means by which to turn them on.

**Comment by TychoWerner** [comment]
> Not sure about the init.py as I don't program, but I tried the manifest.json thing and it hosed my startup. Removed the json file and it fired up again, but now I've lost the ability to automate the house lights in our sanctuary and we have no other means by which to turn them on.

I found about the init.py in this docs... https://developers.home-assistant.io/docs/en/creating_integration_file_structure.html

**Comment by arretx** [comment]
Yeah, I just read that a few times, but it's basically a foreign language.  I sorta get it, but not enough to start tinkering.

**Comment by Rob65** [comment]
I got it working like this:

light.py should be placed in the folder custom_components/dmx.
In that same folder place an empty __init__.py (with just 1 line """DMX Lights""")
and a manifest.json with the following content:
```
{
  "domain": "dmx",
  "name": "DMX Light",
  "documentation": "https://github.com/jnimmo/hass-dmx/",
  "dependencies": [],
  "codeowners": [],
  "requirements": []
}
```

**Comment by arretx** [comment]
YESSSSSSS!  I don't know how you figured that out, but kudos.

**Comment by arretx** [comment]
I created a pull request on jnimmo's repo with these files.

**Comment by Rob65** [comment]
> YESSSSSSS! I don't know how you figured that out, but kudos.

Good to see this is not just one of those "works on my machine" things ;-)

Using this: https://developers.home-assistant.io/docs/en/creating_integration_file_structure.html
I was able to figure out that we now need a directory for the component (previously you could just create a custom_components/dmx.py).

From there on, https://github.com/home-assistant/example-custom-config/tree/master/custom_components/example_light
lead me to the files needed.

**Comment by TychoWerner** [comment]
> > YESSSSSSS! I don't know how you figured that out, but kudos.
> 
> Good to see this is not just one of those "works on my machine" things ;-)
> 
> Using this: https://developers.home-assistant.io/docs/en/creating_integration_file_structure.html
> I was able to figure out that we now need a directory for the component (previously you could just create a custom_components/dmx.py).
> 
> From there on, https://github.com/home-assistant/example-custom-config/tree/master/custom_components/example_light
> lead me to the files needed.

Awesome, going to try it soon as possible. 

Thanks guys for being able to make this work again. Let's see if @jnimmo will merge it. Haven't seen a response from him in while.

**Comment by jnimmo** [comment]
Sorry all I'd updated the IntesisHome platform but forgot about DMX needing rearranging too, and been away for the last couple of days. Thanks for the PR and resolving!
