### ISSUE TITLE
rgbaw lights

### ISSUE THREAD

**Issue by KroniK907** [jnimmo/hass-dmx#25]
Hello,

I have a set of LED panel lights that don't really fit any of the fixture options you have provided. 

It is essentially an rgbaw light. Red, Green, Blue, Amber, White. Each color is individually controllable as its own channel. 

Could you add this fixture type? If you are busy I can take a stab at it but I'm a self taught php & JS programmer with limited python skills, so I'd guess you would do a better job. I can probably use the rgbdw fixture or rgbw fixture and just make that work for now, but I'd like to get all the colors working at some point if I can. 

Thanks!

**Comment by KroniK907** [comment]
Specifically it will need an RGB wheel (Channel 1,2,3), plus a white dimmer slider that adds white. Then a temperature slider that would be an amber and white mix slider, and then a brightness slider that controls the brightness of all 5 channels.

**Comment by jnimmo** [comment]
Home Assistant is a great way to learn Python! 
Is the brightness slider a separate channel, or just 5 channels (RGBAW)?

Do you want the temperature slider to affect RGB values too, or just the temperature for the white light?
I've added a light type RGBAW basically just copying and pasting RGBA - but I'm not sure if it'll be what you're after!

**Comment by jnimmo** [comment]
Closing as no feedback
