### ISSUE TITLE
Only single channel DMX

### ISSUE THREAD

**Issue by filmgarage** [jnimmo/hass-dmx#26]
Anyone know what is going on here? I was forced to update my Home Assistant install because of a crash and I installed the last version of hassocks-dmx using HACS.

Now my fixtures are not working correctly anymore. Looks like they don't address all DMX channels individually. The same value gets set for all channels. Lovelace card shows this one value only as well. Before I used to see all individual DMX values...

Old card:

![IMG_8200](https://user-images.githubusercontent.com/30559371/71323224-27a34e00-24d1-11ea-84eb-4fbe39d502a8.png)

Now looks like this:

![IMG_8217](https://user-images.githubusercontent.com/30559371/71323233-3c7fe180-24d1-11ea-950e-3fd084a8db48.png)

**Comment by jnimmo** [comment]
I haven’t tested it after the latest pull request so I’ll do that when I
get a chance, or see if you can downgrade one version

**Comment by filmgarage** [comment]
Unfortunately I have no idea how to download an older version... :-D

**Comment by filmgarage** [comment]
I managed to dig up some files in a backup, I have it working again. I think this version was final on April 28, 2019. I hope this helps you to find the bug...

**Comment by nordan70** [comment]
I have now tested the newest version and it works for RGB and CT fixtures.
Greate work.
