### ISSUE TITLE
Rename the project to hass-dmx-ip?

### ISSUE THREAD

**Issue by zonque** [jnimmo/hass-dmx#3]
Maybe this project should be called something more generic, and Art-Net should just be one specific mode that can be selected. This would give the project some slack to grow into something that supports multiple other IP based systems?

Just a thought though.

**Comment by jnimmo** [comment]
Yeah good idea - when I started on the project I only knew about Art-Net. Even just hass-dmx would be fine __
I do plan to look at incorporating into the core code once stable
