### ISSUE TITLE
Add support for lights with master dimmer

### ISSUE THREAD

**Issue by zonque** [jnimmo/hass-dmx#4]
I have some DMX lights that allow controlling RGBW channels but have an additional master fader channel. Currently, I set up two light entities for those, one for the RGBW part and one for the master fader, but it would be much nicer to expose them as one light only.

**Comment by jnimmo** [comment]
So you mean the main brightness control would control the brightness over the white LED and RGB?

Have you tried the **rgbw_auto** mode for the RGB channel, it would give you that functionality but doesn't give you a fader for the white channel it just is automatically calculated based on the selected colour

**Comment by zonque** [comment]
Nope, these lamps have R, G, B and W channels, _plus_ a master channel. 5 channels in total.

In order to support these, the brightness (including the transition logic) should be controlled exclusively over this dedicated channel I figure.

**Comment by jnimmo** [comment]
Interesting, will look into it!

**Comment by jnimmo** [comment]
Just noticed this has already been added as RGBWD - cheers!
